tools:
  - name: binny
    version:
      want: v0.13.2
    method: github-release
    with:
      repo: anchore/binny

  - name: task
    version:
      want: v3.53.1
    method: github-release
    with:
      repo: go-task/task

  - name: golangci-lint
    version:
      want: v2.12.2
    method: github-release
    with:
      repo: golangci/golangci-lint

  - name: govulncheck
    version:
      want: v1.7.0
      method: go-proxy
      with:
        module: golang.org/x/vuln
        allow-unresolved-version: true
    method: go-install
    with:
      entrypoint: cmd/govulncheck
      module: golang.org/x/vuln

  - name: osv-scanner
    version:
      want: v2.5.1
    method: github-release
    with:
      repo: google/osv-scanner

  - name: betteralign
    version:
      want: v0.14.4
      method: go-proxy
      with:
        module: github.com/dkorunic/betteralign
        allow-unresolved-version: true
    method: go-install
    with:
      entrypoint: cmd/betteralign
      module: github.com/dkorunic/betteralign

  - name: gosimports
    version:
      want: v0.3.8
    method: github-release
    with:
      repo: rinchsan/gosimports

  - name: goreleaser
    version:
      want: v2.17.1
    method: github-release
    with:
      repo: goreleaser/goreleaser

  - name: actionlint
    version:
      want: v1.7.12
    method: github-release
    with:
      repo: rhysd/actionlint

  - name: zizmor
    version:
      want: v1.29.0
    method: github-release
    with:
      repo: zizmorcore/zizmor
